GET http://localhost:5000/api/users
###
GET http://localhost:5000/api/users/4
###
POST http://localhost:5000/api/user
content-type: application/json

{
    "name": "Gandalf",
    "bio": "AKA Gandalf the Great"
}
###
DELETE "http://localhost:5000/api/user/4"
###
PUT http://localhost:5000/api/user/2
content-type: application/json

{
    "name": "my new name",
    "bio": "about me"
}